services:
  chess-engine:
    build:
      context: .
      dockerfile: Dockerfile
    image: chess-engine:latest
    container_name: chess-engine
    environment:
      FLASK_MODE: "flask"
      FLASK_APP_MODULE: "/app/health_check.py"
      FLASK_HOST: "0.0.0.0"
      FLASK_PORT: "5000"
      # ENGINE_MQTT_BIN: "/app/build/engine_mqtt"
      CHESS_CLI_BIN: "/app/build/chess_cli"
      MQTT_HOST: "mosquitto"
      MQTT_PORT: "1883"
      MQTT_CLIENT_ID: "chess_engine"

    ports:
      - "5000:5000"

    networks:
      - chess-network

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  chess-network:
    external: true
    name: symfony-chess-backend_chess-network
